/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type OrderStatus = "CANCELLED" | "DELIVERED" | "PAID" | "PENDING" | "SHIPPED";

export type PaymentMethod = "COD" | "PAYSTACK" | "STRIPE";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Brands {
  brand_id: Generated<number>;
  description: string | null;
  name: string;
}

export interface Cart {
  cart_id: Generated<number>;
  created_at: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface CartItem {
  cart_id: number;
  id: Generated<number>;
  quantity: number;
  variant_id: number | null;
}

export interface Categories {
  category_id: Generated<number>;
  description: string | null;
  name: string;
  parent_id: number | null;
  slug: string;
}

export interface OrderItem {
  id: Generated<number>;
  order_id: number | null;
  price: number;
  quantity: number;
  variant_id: number | null;
}

export interface Orders {
  created_at: Generated<Timestamp | null>;
  order_id: Generated<number>;
  payment: PaymentMethod | null;
  shipping_address: string | null;
  status: Generated<OrderStatus>;
  total_amount: number;
  user_id: number | null;
}

export interface Products {
  brand_id: number | null;
  category_id: number | null;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  discount_percentage: number | null;
  image_url: string | null;
  is_active: Generated<boolean | null>;
  name: string;
  price: number;
  product_id: Generated<number>;
  slug: string;
}

export interface ProductVariants {
  color: string | null;
  product_id: number;
  size: string | null;
  sku: string | null;
  stock: number;
  variant_id: Generated<number>;
}

export interface ResetTokens {
  email: string;
  expiration: Timestamp | null;
  id: Generated<number>;
  token: string;
  used: Generated<boolean>;
}

export interface Reviews {
  content: string | null;
  created_at: Generated<Timestamp | null>;
  product_id: number | null;
  rating: number | null;
  review_id: Generated<number>;
  user_id: number | null;
}

export interface Sessions {
  data: Json | null;
  expires_at: Timestamp | null;
  id: string;
}

export interface Users {
  address: string | null;
  city: string | null;
  country: string | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  fullname: string | null;
  gender: string | null;
  google_id: string | null;
  password: string | null;
  phone: string | null;
  roles: Generated<string[]>;
  state: string | null;
  user_id: Generated<number>;
  username: string;
}

export interface Wishlists {
  id: Generated<number>;
  product_id: number | null;
  user_id: number | null;
}

export interface DB {
  brands: Brands;
  cart: Cart;
  cart_item: CartItem;
  categories: Categories;
  order_item: OrderItem;
  orders: Orders;
  product_variants: ProductVariants;
  products: Products;
  resetTokens: ResetTokens;
  reviews: Reviews;
  sessions: Sessions;
  users: Users;
  wishlists: Wishlists;
}
